import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ITMED home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bienvenue chez <a href="#">ITMED</a>
        </h1>

      

        <div className={styles.grid}>
          <a href="https://itmedlinge-pic51w0h2-aymanedroussi.vercel.app/auth" className={styles.card}>
            <h2>CLEANLINE &rarr;</h2>
            <p>une application  pour organiser et sécuriser le servide de linge .</p>
          </a>

          <a href="https://dpi-gzld8mam2-tahafi2001.vercel.app/auth" className={styles.card}>
            <h2>DOSSIER PATIENT &rarr;</h2>
            <p>une application  pour gérer les patients au sein d un hôpital.</p>
          </a>

          <a
            href="https://cuisineitmed-eniwzdba6-tahafi2001.vercel.app/"
            className={styles.card}
          >
            <h2>CUISINE &rarr;</h2>
            <p>une application  pour organiser et sécuriser le servide de cuisine .</p>
          </a>

          <a
            href="https://pharmacie-10.herokuapp.com/"
            className={styles.card}
          >
            <h2>PHARMACIE &rarr;</h2>
            <p>
            une application web pour organiser et sécuriser les services d une pharmacie  .
            </p>
          </a>
          <a
            href="https://gestion-des-dechets-next.vercel.app/auth"
            className={styles.card}
          >
            <h2>Déchet &rarr;</h2>
            <p>
            une application  pour organiser et sécuriser le servide de déchet .
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
         All right reserved 2022
        
        </a>
      </footer>
    </div>
  )
}
